### ISSUE TITLE
Taggle v1.12.0

### ISSUE THREAD

**Issue by Hitabis** [hsgubert/taggle#1]
Any plans to update to [Taggle v1.12.0](https://github.com/okcoker/taggle.js/releases/tag/1.12.0)?

**Comment by hsgubert** [comment]
Hi @Hitabis , I'm really short on time right now. Do you know how to do it? If so I can accept your pull request and launch the new version of the gem sometime tomorrow or monday.

**Comment by Hitabis** [comment]
I'll have to:

1. Import the following files from [okcoker/taggle.js](https://github.com/okcoker/taggle.js/tree/9bf5be251d6eb1f6ca7c88c660350faaa9c2cd95/src):

- [taggle-ie8.js](https://github.com/okcoker/taggle.js/blob/9bf5be251d6eb1f6ca7c88c660350faaa9c2cd95/src/taggle-ie8.js)
- [taggle-ie9.js](https://github.com/okcoker/taggle.js/blob/9bf5be251d6eb1f6ca7c88c660350faaa9c2cd95/src/taggle-ie9.js)
- [taggle.js](https://github.com/okcoker/taggle.js/blob/9bf5be251d6eb1f6ca7c88c660350faaa9c2cd95/src/taggle.js)

2. Bump the version in [taggle/lib/taggle/version.rb](https://github.com/hsgubert/taggle/blob/b4e2dca03b3cd4918a11d19677c972bb989e58ee/lib/taggle/version.rb)

Am I missing something @hsgubert ?

**Comment by hsgubert** [comment]
Also update css files if necessary and update README, that should be it

**Comment by hsgubert** [comment]
Thanks, btw
